version: '3.1'

volumes:
  mysql_data:


services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - mysql_data:/var/lib/myqsl
    restart: always
